### ISSUE TITLE
--burnafterreading doesn't work ? 

### ISSUE THREAD

**Issue by rylebrun** [amine7536/privatebin-cli#8]
Hi, 
Trying : 
`privatebin --url https://privatebin.net --expire 5min --burnafterreading --output json 'Hello World !'`
or
`privatebin --url https://privatebin.net --burnafterreading --output json 'Hello World !'`
but the **Burn after reading** feature doesn't work. Any tips ?
Thanks,

**Comment by rylebrun** [comment]
See here for a dirty quick fix : https://github.com/PrivateBin/PrivateBin/issues/566#issuecomment-575229530

**Comment by rugk** [comment]
Maybe do send them a PR here to fix i?

**Comment by rylebrun** [comment]
@rugk, my 'solution' is a little bit dirty and it's not the correct behavior of this CLI because it's hardcoded (and the option --burnafterreading doesn't work).
